Unit-1,2,3
  --WAP Concept of Class & Objects
  --Concept of Inheritance
  --Concept of OverRiding
  --Concept of Polymorphism & Defination & exapmples
  --Constructor & Method OverLoading
  --Constructor Chaining
Unit-4,5,6
  --Interfaces
    --Defination & example
	--Description & Details About Comparator Interface
  --Inner Class 
    --Concept of nested class
	--Concept of inner class
  --LambdaExpression
  --Exception Handling
    --try with multiple catch & finally block
	--WAP concept of Explicit Handler
	--WAP one try with  multiple catches
	--WAP concept of finally block
	--Custom exception(using throw keyword,handle CE by user)
	--propagation of exception
	--How to declare & check the Checked Exceptions(using throws keyword)
  --IO
    --WAP read & write data to & from a file using Scanner & printwriter methods
	--WAP read & write data to a file in form of Charcter oriented format
	--WAP read & write data to & from a file by byte oriented format
	--WAP read & write data to & from a file using IO Streams
	--WAP read & write data to & from a file using File input& output Streams
	--Concept of Serializibality & de-Serializibality
	--Read & Write data of object of to & from a file
	--Read & write data of object using IO streams
	--Copy from one-ANother
  --generics
    --Defiantion & examples
	--concept of Two type Parameters
	--WAP concept of Generic is constraint is just dealing with.......
	--Bounded Generics
  --Collection 
    --Types of Methods in Collection(TreeSet,queue,ArrayList,HashMap)(Explain the methods which are in common/general in all types)
	--Concept of ArrayList,TreeSet,De-Queue,HashMap
	--concept of Hash Value Pair
	
Diamond class.......