{
  # CALLING LIBRARIES
  install.packages('pairs.panels')
  library(psych)
  library(pairs.panels)
  
  # GETTING DATA
  DATA=iris
  
  # VIEWING DATA
  str(DATA)
  summary(DATA)
  
  # NON PROBABILITIC SAMPLING
  NONPROBABILITIC=iris[1:50,]
  summary(NONPROBABILITIC)
  
  # DATA SUBSETTING AND PREPARATION
  set.seed(1234)
  
  TRAINING=NONPROBABILITIC[1:35,-5]
  TESTING=NONPROBABILITIC[36:50,-5]
  summary(TRAINING)
  summary(TESTING)
  
  
  # CREATING MULTIPLE LINEAR REGRESSION MODEL
  MODEL=lm(Sepal.Width~.,data=TRAINING)
  summary(MODEL)
  
  
  # PLOTTING MODEL
  p=plot(TRAINING$Sepal.Length,TRAINING$Sepal.Width)
  abline(MODEL,col='red')
  cor(iris[1:49,1:4])
  pairs.panels(iris[1:49,1:4])
  
  
  # CREATING MODEL FOR SIGNIFICANT COLUMN
  MODEL=lm(Sepal.Width~Sepal.Length,data=TRAINING)
  summary(MODEL)
  
  # PLOTTING MODEL AGAIN FOR SIGNIFICANT COLUMN
  q=plot(TRAINING$Sepal.Length,TRAINING$Sepal.Width)
  abline(MODEL,col='red')
  
  
  # PREDICTION
  summary(TRAINING)
  #(PREDICTION=predict(MODEL,TESTING[c(1,3,4)]))
  (PREDICTION=predict(MODEL,TESTING[c(1)]))
  cbind(TESTING[2],PREDICTION)
  
  # PREDICTION FOR PARTICULAR ROW
  CHECK=TESTING[10,]
  CHECK
  #(PREDICTED_VALUE=predict(MODEL,CHECK[c(1,3,4)]))
  (PREDICTED_VALUE=predict(MODEL,CHECK[c(1)]))
  (VALUE=data.frame(ACTUAL_VALUE=CHECK[,2],PREDICTED_VALUE))
 
  
  # FINDING ERROR PERCENTAGE AND ACCURACY
  DIFFERENCE=abs(TESTING[,2]-PREDICTION)
  ERROR_PERCENTAGE=DIFFERENCE/TESTING[,2]*100
  ACCURACY_PERCENTAGE=100-ERROR_PERCENTAGE
  (cbind(ACTUAL=TESTING[,2],PREDICTED=PREDICTION,ERROR=DIFFERENCE,ERROR_PERCENTAGE,ACCURACY_PERCENTAGE))
  mean(ACCURACY_PERCENTAGE)
}
                     