LUNGCAP=read.csv(file.choose(),sep=',',header = T)
attach(LUNGCAP)
names(LUNGCAP)
summary(LUNGCAP)
class(LUNGCAP$Age)
plot(Age,LungCap, main="scatterplot")
cor(Age,LungCap)
LINEARMODEL=lm(LungCap~Age)
summary(LINEARMODEL)
attributes(LINEARMODEL)
plot(Age, LungCap, main="scatterplot")
abline(LINEARMODEL,col=2, lwd=3)
confint(LINEARMODEL)
confint(LINEARMODEL, level=0.99)
anova(LINEARMODEL)
checkLUNGS=data.frame(Age=5)
result=predict(LINEARMODEL,checkLUNGS)
result
